export default {
  en: {
    wizard_title: 'Have an idea of your own? ',
    wizard_intro: 'That\'s awesome! We will show you a live preview of your post on the right as we walk you through the process on the left.',
    wizard_title2: 'Let\'s get down to basics',
    wizard_exhibit_name: 'Exhibit name',
    wizard_short_summary: 'Short summary',
    wizard_select_thumbnail: 'Select thumbnail',
    wizard_additional_images: 'Additional images',
    wizard_inspiration: 'What\'s your inspiration in this exhibit?',
    wizard_complex: 'Now to some more complex things',
    wizard_provided: 'Provided us with a detailed descritption of this exhibit including all nessicary background knowledge.',
    wizard_tellus: 'Tell us the kind of things you want to see in this exhibit.',
    wizard_title3: 'Time to double check',
    wizard_looksgreat: 'Make sure everything look good over in the preview and then click Finish.',
    wizard_selectfiles: 'files selected',
    wizard_thumbnail: 'thumbnail selected',
    wizard_addTags: 'Add tags to your exhibit*',
    wizard_inviteFriends: 'Collaborate with your friends!',
    wizard_sendInvite: 'Send invite',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    preview: 'Preview'
  },
  es: {
    wizard_title: 'Holla',
    wizard_intro: 'That\'s awesome! We will show you a live preview of your post on the right as we walk you through the process on the left.',
    wizard_title2: 'Let\'s get down to basics',
    wizard_exhibit_name: 'Exhibit name',
    wizard_short_summary: 'Short summary',
    wizard_select_thumbnail: 'Select thumbnail',
    wizard_additional_images: 'Additional images',
    wizard_inspiration: 'What\'s your inspiration in this exhibit?',
    wizard_complex: 'Now to some more complex things',
    wizard_provided: 'Provided us with a detailed descritption of this exhibit including all nessicary background knowledge.',
    wizard_tellus: 'Tell us the kind of things you want to see in this exhibit.',
    wizard_title3: 'Time to double check',
    wizard_looksgreat: 'Make sure everything look good over in the preview and then click Finish.',
    wizard_selectfiles: 'files selected',
    wizard_thumbnail: 'thumbnail selected',
    wizard_addTags: 'Add tags to your exhibit*',
    wizard_inviteFriends: 'Collaborate with your friends!',
    wizard_sendInvite: 'Send invite',
    next: 'Next',
    back: 'Back',
    finish: 'Finish',
    preview: 'Preview'
  }
}
